AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nature-remo-sam-dynamo
  
  Sample SAM Template for nature-remo-sam-dynamo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  RemoGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: nature-remo/
      Handler: nature-remo
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetNatureRemo:
          Type: Api
          Properties:
            Path: /nature-remo
            Method: GET
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
          DYNAMODB_TABLE_NAME: !Ref RemoDynamoDBTable
          NATURE_REMO_ACCESS_TOKEN: ""
  RemoPutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: nature-remo/
      Handler: nature-remo
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetNatureRemo:
          Type: Api
          Properties:
            Path: /nature-remo
            Method: POST
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
          DYNAMODB_TABLE_NAME: !Ref RemoDynamoDBTable
          NATURE_REMO_ACCESS_TOKEN: ""
  RemoDynamoDBTable:
    Type: AWS::Serverless::SimpleTable # DyanmoDB resource
    Properties:
      PrimaryKey:
        Name: Date
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NatureRemoAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  RemoGetFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt RemoGetFunction.Arn
  RemoGetFunctionIamRole:
    Description: "Implicit IAM Role created for Remo function"
    Value: !GetAtt RemoGetFunctionRole.Arn
  RemoPutFunction:
    Description: "First Lambda Function ARN"
    Value: !PutAtt RemoPostFunction.Arn
  RemoPutFunctionIamRole:
    Description: "Implicit IAM Role created for Remo function"
    Value: !PutAtt RemoPostFunctionRole.Arn
